[build]
  publish = "public"   # Diretório de publicação para arquivos estáticos (caso tenha)
  command = "pip install -r requirements.txt"  # Comando para instalar as dependências

[functions]
  directory = "netlify/functions"  # Diretório onde estarão as funções serverless
  node_bundler = "esbuild"  # Para melhor otimização do build de funções (se necessário)

[env]
  PYTHON_VERSION = "3.9"