[build]
  publish = "public"
  command = "pip install --no-cache-dir -r requirements.txt"
  environment = { NETLIFY_PYTHON_VERSION = "3.9" }

[functions]
  directory = "netlify/functions"
  
[env]
  PYTHON_VERSION = "3.9"
  PATH = "/usr/pgsql-13/bin:$PATH"