[build]
    command = "pip install -r requirements.txt && gunicorn netlify.functions.app:app"
    environment = { NETLIFY_PYTHON_VERSION = "3.13" }
    publish = "static"  # Indica o diretório de funções (ou outro diretório relevante)
    functions = "functions"
  
[functions]
  directory = "netlify/functions"  # Diretório onde as funções serverless estão localizadas

[env]
  PYTHON_VERSION = "3.13"
  PATH = "/usr/pgsql-13/bin:$PATH"
  FLASK_APP = "netlify/functions/app.py"
  FLASK_ENV = "production"
