[build]
  command: 'pip install --no-cache-dir --only-binary :all: -r requirements.txt'
  commandOrigin: config
  publishOrigin: config
  publish: /opt/build/repo

[functions]
    directory: /opt/build/repo/netlify/functions

[env]
  PYTHON_VERSION = "3.9"
