[build]
  command = "pip install --no-cache-dir --only-binary :all: -r requirements.txt"
  environment = { NETLIFY_PYTHON_VERSION = "3.9" }
  publish = "build"  # Indica um diretório de build, mesmo que o diretório "public" não seja usado
  functions = "netlify/functions"  # Diretório para funções serverless, caso exista

[functions]
  directory = "netlify/functions"  # Caso haja funções serverless no Netlify

[env]
  PYTHON_VERSION = "3.9"
  PATH = "/usr/pgsql-13/bin:$PATH"
