[build]
  publish = "public"
  command = "pip install -r requirements.txt --no-cache-dir"

[functions]
  directory = "netlify/functions"
  
[env]
  PYTHON_VERSION = "3.9"
  PATH = "/usr/pgsql-13/bin:$PATH"