[build]
  command = "pip install --no-cache-dir --only-binary :all: -r requirements.txt"
  environment = { NETLIFY_PYTHON_VERSION = "3.9" }
  publish = "."  # Define o diretório raiz como o diretório de publicação, já que não há diretório 'public'

[functions]
  directory = "netlify/functions"  # Localização das funções serverless do Netlify

[env]
  PYTHON_VERSION = "3.9"
  PATH = "/usr/pgsql-13/bin:$PATH"
