[build]
  command = "pip install --no-cache-dir --only-binary :all: -r requirements.txt"
  environment = { NETLIFY_PYTHON_VERSION = "3.9" }
  publish = "C:\Users\aliso\OneDrive\Documentos\Projeto-Portfólio"  # Indica o diretório de funções (ou outro diretório relevante)
  
[functions]
  directory = "netlify/functions"  # Diretório onde as funções serverless estão localizadas

[env]
  PYTHON_VERSION = "3.9"
  PATH = "/usr/pgsql-13/bin:$PATH"
