[build]
  command = "pip install --no-cache-dir --only-binary :all: -r requirements.txt"
  functions = "netlify/functions"
  publish = "/"

[functions]
  directory = "netlify/functions"  # Define a pasta onde as funções serverless estão localizadas

[env]
  PYTHON_VERSION = "3.9"
